server:
  port: 8088

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#一些总的配置文件
spring:
  aop:
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    readSize: 2
  devtools:
    restart:
      enabled: true
  mvc:
    servlet:
      load-on-startup: 0
  http:
    encoding:
      force: true
  freemarker:
      allow-request-override: false
      cache: true
      check-template-location: true
      charset: utf-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      suffix: .ftl
      templateLoaderPath: classpath:/templates/
      expose-spring-macro-helpers: false
      #应用程序发布，如果有上下文路径，则可以使用
      request-context-attribute: request
  jackson:
    default-property-inclusion:
mybatis:
  type-aliases-package: simm.learning.biz.entity

#spring:
#  application:
#    name: mybatis
#  datasource:
#      name: test
#      url: jdbc:mysql://127.0.0.1:3306/mytest
#      username: root
#      password: admin
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#mybatis:
#  type-aliases-package: simm.learning.biz.entity
#  mapper-locations: classpath:mapper/*.xml:
